# Generated by Django 5.2.7 on 2025-12-08 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestuser",
            name="fingerprint",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="guestuser",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guestuser",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("ai", "AI")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="guestuser",
            name="last_used",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
